CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS seats_db;
CREATE DATABASE IF NOT EXISTS skybooker_db;
CREATE DATABASE IF NOT EXISTS passenger_db;
CREATE DATABASE IF NOT EXISTS booking_db;
CREATE DATABASE IF NOT EXISTS payment_db;
CREATE DATABASE IF NOT EXISTS notification_db;